### PR TITLE
Reference secrets availabe in cbi-pass

### PR DESCRIPTION
**Pull request by netomi**
This PR references known secrets as available in the cbi-pass repo maintained by the EF.

There are still 2 tokens left.

### CODE REVIEW

**Comment by netomi** [comment]
Can you take a look at the PR @jonahgraham  ? Do you have an idea about the 2 other secrets:

- VS_MARKETPLACE_TOKEN
- GH_ACTION_TOKEN

**Comment by jonahgraham** [comment]
@netomi - no, I don't know, but @sdirix and @thegecko probably know about them.

**Comment by thegecko** [comment]
I'm unsure of the question here. These tokens are for managing publishes to the VS Code and OpenVSX marketplaces from GitHub actions.

**Comment by netomi** [comment]
To give some context about this repo: it is a new approach of the EF so provide some kind of self-service to projects wrt GitHub resources. For this purpose the current live configuration of this organization is captured in a configuration file (https://github.com/eclipse-cdt-cloud/.eclipsefdn/blob/main/otterdog/eclipse-cdt-cloud.jsonnet). This includes various organization and repository secrets. We also would like to store the actual secret values in some credential provider managed by the EF , so we have a central place where theses values are kept for reference, and we can also update them if needed and push the changes to GitHub. For 2 secrets the value is not known to me atm, if you have information, especially the VS_MARKETPLACE_TOKEN, please let me know.

**Comment by thegecko** [comment]
These were created by Sébastien Heurtematte over in:

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2978

**Comment by netomi** [comment]
ty, I will ping him about the secret, also good to learn about the ongoing issues with the vsx token.

**Pull request merged**
